import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const guard = "Use only when the user explicitly requests this skill.";
const siteUrl = "https://skills.tailrocks.com";
const repoBlob = "https://github.com/tailrocks/tailrocks-skills/blob/main";
const banner = "<!-- Generated by scripts/generate-docs.ts. Edit the skill source, not this file. -->";
const listStart = "<!-- skills:start -->";
const listEnd = "<!-- skills:end -->";

export interface Skill {
  readonly name: string;
  readonly title: string;
  readonly summary: string;
  readonly description: string;
  readonly argumentHint: string | undefined;
  readonly defaultPrompt: string | undefined;
  readonly body: string;
  readonly references: readonly string[];
  readonly templates: readonly string[];
}

export interface Generated {
  readonly file: string;
  readonly content: string;
}

export interface Group {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly skills: readonly string[];
}

export interface GroupedSkills {
  readonly group: Group;
  readonly skills: readonly Skill[];
}

export async function readCatalog(root: string): Promise<Group[]> {
  const parsed = JSON.parse(await readFile(path.join(root, "catalog.json"), "utf8")) as { groups?: unknown };
  if (!Array.isArray(parsed.groups)) throw new Error("catalog.json: groups must be an array");
  return parsed.groups as Group[];
}

/** Orders skills by catalog group, and refuses a catalog that does not cover the tree exactly once. */
export function groupSkills(groups: readonly Group[], skills: readonly Skill[]): GroupedSkills[] {
  const byName = new Map(skills.map((skill) => [skill.name, skill]));
  const placed = new Set<string>();
  const grouped: GroupedSkills[] = [];

  for (const group of groups) {
    const members: Skill[] = [];
    for (const name of group.skills) {
      const skill = byName.get(name);
      if (!skill) throw new Error(`catalog.json: group ${group.id} lists unknown skill ${name}`);
      if (placed.has(name)) throw new Error(`catalog.json: ${name} appears in more than one group`);
      placed.add(name);
      members.push(skill);
    }
    grouped.push({ group, skills: members });
  }

  const ungrouped = skills.filter((skill) => !placed.has(skill.name)).map((skill) => skill.name);
  if (ungrouped.length > 0) throw new Error(`catalog.json: no group contains ${ungrouped.join(", ")}`);
  return grouped;
}

/** Applies `transform` to prose only, leaving fenced blocks and inline code spans untouched. */
export function mapProse(source: string, transform: (text: string) => string): string {
  let fenced = false;
  return source
    .split("\n")
    .map((line) => {
      if (/^\s*```/.test(line)) {
        fenced = !fenced;
        return line;
      }
      if (fenced) return line;
      return line
        .split(/(`[^`]*`)/g)
        .map((part) => (part.startsWith("`") ? part : transform(part)))
        .join("");
    })
    .join("\n");
}

/** Rewrites repository-relative markdown links to absolute blob URLs. */
export function absoluteLinks(source: string, base: string): string {
  return mapProse(source, (text) =>
    text.replace(/\]\(([^)]+)\)/g, (match, target: string) =>
      /^(?:https?:|mailto:|#)/.test(target) ? match : `](${base}/${target})`,
    ),
  );
}

/** Escapes the characters MDX would otherwise read as expression or JSX syntax. */
export function escapeMdx(source: string): string {
  return mapProse(source, (text) =>
    text
      .replace(/<((?:https?|mailto):[^>\s]+)>/g, "[$1]($1)")
      .replace(/</g, "&lt;")
      .replace(/\{/g, "&#123;")
      .replace(/\}/g, "&#125;"),
  );
}

/** Strips the explicit-request guard and returns the first remaining sentence. */
export function summarize(description: string): string {
  const remainder = description.startsWith(guard)
    ? description.slice(guard.length).trim()
    : description.trim();
  const stop = remainder.search(/\.\s/);
  return stop === -1 ? remainder : remainder.slice(0, stop + 1);
}

function withoutGuard(description: string): string {
  return description.startsWith(guard) ? description.slice(guard.length).trim() : description.trim();
}

function titleFrom(body: string, name: string): string {
  return body.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? name;
}

function bodyWithoutTitle(body: string): string {
  return body.replace(/^#\s+.+\n+/, "").trimEnd();
}

async function listFiles(directory: string): Promise<string[]> {
  try {
    const entries = await readdir(directory, { withFileTypes: true, recursive: true });
    return entries
      .filter((entry) => entry.isFile())
      .map((entry) => path.relative(directory, path.join(entry.parentPath, entry.name)))
      .sort();
  } catch {
    return [];
  }
}

export async function readSkill(root: string, name: string): Promise<Skill> {
  const skillDir = path.join(root, "skills", name);
  const source = await readFile(path.join(skillDir, "SKILL.md"), "utf8");
  const block = source.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!block) throw new Error(`${name}: invalid frontmatter`);
  const metadata = Bun.YAML.parse(block[1]) as Record<string, unknown>;
  const description = typeof metadata.description === "string" ? metadata.description : "";
  const body = source.slice(block[0].length).trim();

  let defaultPrompt: string | undefined;
  try {
    const openai = Bun.YAML.parse(await readFile(path.join(skillDir, "agents", "openai.yaml"), "utf8")) as {
      interface?: { default_prompt?: unknown };
    };
    if (typeof openai.interface?.default_prompt === "string") defaultPrompt = openai.interface.default_prompt;
  } catch {
    defaultPrompt = undefined;
  }

  return {
    name,
    title: titleFrom(body, name),
    summary: summarize(description),
    description: withoutGuard(description),
    argumentHint: typeof metadata["argument-hint"] === "string" ? metadata["argument-hint"] : undefined,
    defaultPrompt,
    body: bodyWithoutTitle(body),
    references: await listFiles(path.join(skillDir, "references")),
    templates: await listFiles(path.join(skillDir, "templates")),
  };
}

function assetSection(skill: Skill, link: (file: string) => string): string {
  const lines: string[] = [];
  if (skill.references.length > 0) {
    lines.push("", "## References", "");
    for (const file of skill.references) lines.push(`- [\`${file}\`](${link(`references/${file}`)})`);
  }
  if (skill.templates.length > 0) {
    lines.push("", "## Templates", "");
    for (const file of skill.templates) lines.push(`- [\`${file}\`](${link(`templates/${file}`)})`);
  }
  return lines.join("\n");
}

function invocation(skill: Skill): string {
  const lines = [
    "## Invocation",
    "",
    "This skill never activates on its own. Name it in your request:",
    "",
    `> Use \`${skill.name}\` …`,
  ];
  if (skill.argumentHint !== undefined) lines.push("", `Arguments: \`${skill.argumentHint}\``);
  return lines.join("\n");
}

/** The documentation-site variant: the invocation is written for the reader's own client. */
function invocationPage(skill: Skill): string {
  const args = skill.argumentHint ?? "";
  const lines = [
    "## Invocation",
    "",
    "This skill never activates on its own. Name it in your request, in the",
    "syntax of the client you use:",
    "",
    "<AgentPicker />",
    "",
    `<Invoke skill="${skill.name}"${args === "" ? "" : ` args="${escapeAttribute(args)}"`} />`,
  ];
  if (skill.argumentHint !== undefined) {
    lines.push("", `Arguments: \`${skill.argumentHint}\``);
  }
  return lines.join("\n");
}

function escapeAttribute(value: string): string {
  return value.replaceAll('"', "'");
}

export function renderReadme(skill: Skill): string {
  return `${banner}

# ${skill.title}

\`${skill.name}\` — part of [tailrocks-skills](../../README.md) · [documentation](${siteUrl}/docs/skills/${skill.name})

${skill.description}

${invocation(skill)}

## Skill definition

The text below is the skill body loaded by the agent, verbatim from
[\`SKILL.md\`](SKILL.md).

---

${skill.body}
${assetSection(skill, (file) => file)}
`;
}

export function renderSkillPage(skill: Skill): string {
  const base = `${repoBlob}/skills/${skill.name}`;
  const body = escapeMdx(absoluteLinks(skill.body, base));
  return `---
title: ${skill.title}
description: ${JSON.stringify(skill.summary)}
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

\`${skill.name}\` · [source](${base}/SKILL.md) · [README](${base}/README.md)

${escapeMdx(skill.description)}

${invocationPage(skill)}

## Skill definition

The text below is the skill body loaded by the agent, verbatim from its source.

---

${body}
${escapeMdx(assetSection(skill, (file) => `${base}/${file}`))}
`;
}

function groupTable(grouped: GroupedSkills, link: (skill: Skill) => string): string {
  const rows = grouped.skills.map((skill) => `| [\`${skill.name}\`](${link(skill)}) | ${skill.summary} |`);
  return [
    `### ${grouped.group.title}`,
    "",
    grouped.group.summary,
    "",
    "| Skill | What it does |",
    "|---|---|",
    ...rows,
  ].join("\n");
}

export function renderSkillIndex(grouped: readonly GroupedSkills[]): string {
  const sections = escapeMdx(
    grouped.map((entry) => groupTable(entry, (skill) => `/docs/skills/${skill.name}`)).join("\n\n"),
  );
  return `---
title: Skills
description: "Every skill in the collection, grouped by the work it belongs to."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

Every skill is manual-only: it runs when you name it, never on its own. When
more than one could apply, [choosing a skill](/docs/choosing) has the ownership
boundaries.

${sections}
`;
}

export function renderSkillMeta(grouped: readonly GroupedSkills[]): string {
  const pages = ["index"];
  for (const entry of grouped) {
    pages.push(`---${entry.group.title}---`);
    for (const skill of entry.skills) pages.push(skill.name);
  }
  return `${JSON.stringify({ title: "Skills", pages }, null, 2)}\n`;
}

export function renderRootList(grouped: readonly GroupedSkills[]): string {
  const sections = grouped
    .map((entry) => groupTable(entry, (skill) => `skills/${skill.name}/README.md`))
    .join("\n\n");
  return `${listStart}

${sections}

${listEnd}`;
}

export function replaceRootList(readme: string, list: string): string {
  const start = readme.indexOf(listStart);
  const end = readme.indexOf(listEnd);
  if (start === -1 || end === -1)
    throw new Error(`README.md is missing the ${listStart} / ${listEnd} markers`);
  return `${readme.slice(0, start)}${list}${readme.slice(end + listEnd.length)}`;
}

export function renderInstallPage(install: string): string {
  const body = escapeMdx(absoluteLinks(install.replace(/^#\s+.+\n+/, "").trimEnd(), repoBlob));
  return `---
title: Installing
description: "Install the collection in Claude Code, Codex, OpenCode, Grok Build, Kimi Code, Antigravity, or Amp."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

${body}
`;
}

export async function generate(root: string): Promise<Generated[]> {
  const names = (await readdir(path.join(root, "skills"), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const skills: Skill[] = [];
  for (const name of names) skills.push(await readSkill(root, name));
  const grouped = groupSkills(await readCatalog(root), skills);

  const output: Generated[] = [];
  for (const skill of skills) {
    output.push({ file: path.join("skills", skill.name, "README.md"), content: renderReadme(skill) });
    output.push({
      file: path.join("docs", "content", "docs", "skills", `${skill.name}.mdx`),
      content: renderSkillPage(skill),
    });
  }
  output.push({
    file: path.join("docs", "content", "docs", "skills", "index.mdx"),
    content: renderSkillIndex(grouped),
  });
  output.push({
    file: path.join("docs", "content", "docs", "skills", "meta.json"),
    content: renderSkillMeta(grouped),
  });
  output.push({
    file: path.join("docs", "content", "docs", "install.mdx"),
    content: renderInstallPage(await readFile(path.join(root, "INSTALL.md"), "utf8")),
  });
  output.push({
    file: "README.md",
    content: replaceRootList(await readFile(path.join(root, "README.md"), "utf8"), renderRootList(grouped)),
  });
  return output;
}

/**
 * Finds diagrams drawn as text instead of Mermaid. A fenced block qualifies when it
 * spans more than one line and uses flow arrows. Directory trees are drawings of a
 * filesystem, not of a flow, so box-drawing characters exempt a block.
 */
export function textDiagrams(source: string): number[] {
  const lines = source.split("\n");
  const found: number[] = [];
  let opened: number | undefined;
  let language = "";
  let body: string[] = [];

  for (const [index, line] of lines.entries()) {
    const fence = line.match(/^\s*```(\w*)/);
    if (!fence) {
      if (opened !== undefined) body.push(line);
      continue;
    }
    if (opened === undefined) {
      opened = index;
      language = fence[1] ?? "";
      body = [];
      continue;
    }
    const isTree = body.some((entry) => /[├└│]/.test(entry));
    const hasArrows = body.some((entry) => /[→⇄↕⟶]|-->/.test(entry));
    if (language !== "mermaid" && hasArrows && !isTree && body.length > 1) found.push(opened + 1);
    opened = undefined;
  }
  return found;
}

/** Fumadocs content is MDX only; a plain .md page silently renders without component support. */
export async function strayMarkdown(root: string): Promise<string[]> {
  const contentRoot = path.join(root, "docs", "content");
  const stray: string[] = [];
  for (const file of await listFiles(contentRoot)) {
    if (file.endsWith(".md")) stray.push(path.join("docs", "content", file));
  }
  return stray.sort();
}

async function currentContent(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

if (import.meta.main) {
  const root = path.resolve(import.meta.dir, "..");
  const check = process.argv.includes("--check");
  const stray = await strayMarkdown(root);
  if (stray.length > 0) {
    for (const file of stray) console.error(`error: documentation pages must be .mdx, not .md: ${file}`);
    process.exit(1);
  }

  const drawn: string[] = [];
  for (const page of await listFiles(path.join(root, "docs", "content"))) {
    if (!page.endsWith(".mdx")) continue;
    const file = path.join("docs", "content", page);
    for (const line of textDiagrams(await readFile(path.join(root, file), "utf8"))) {
      drawn.push(`${file}:${line}`);
    }
  }
  if (drawn.length > 0) {
    for (const at of drawn) console.error(`error: draw this as a \`\`\`mermaid diagram, not text: ${at}`);
    process.exit(1);
  }
  const generated = await generate(root);
  const stale: string[] = [];
  for (const { file, content } of generated) {
    const target = path.join(root, file);
    if ((await currentContent(target)) === content) continue;
    stale.push(file);
    if (check) continue;
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content);
  }
  if (check && stale.length > 0) {
    for (const file of stale) console.error(`error: out of date, run 'mise run docs': ${file}`);
    process.exit(1);
  }
  console.log(
    check
      ? `Checked ${generated.length} generated files.`
      : `Wrote ${stale.length}/${generated.length} files.`,
  );
}
