import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const guard = "Use only when the user explicitly requests this skill.";
const siteUrl = "https://skills.tailrocks.com";
const repoBlob = "https://github.com/tailrocks/tailrocks-skills/blob/main";
const banner = "<!-- Generated by scripts/generate-docs.ts. Edit the skill source, not this file. -->";
const listStart = "<!-- skills:start -->";
const listEnd = "<!-- skills:end -->";

export interface Skill {
  readonly name: string;
  readonly title: string;
  readonly summary: string;
  readonly description: string;
  readonly argumentHint: string | undefined;
  readonly defaultPrompt: string | undefined;
  readonly body: string;
  readonly references: readonly string[];
  readonly templates: readonly string[];
}

export interface Generated {
  readonly file: string;
  readonly content: string;
}

/** Applies `transform` to prose only, leaving fenced blocks and inline code spans untouched. */
export function mapProse(source: string, transform: (text: string) => string): string {
  let fenced = false;
  return source
    .split("\n")
    .map((line) => {
      if (/^\s*```/.test(line)) {
        fenced = !fenced;
        return line;
      }
      if (fenced) return line;
      return line
        .split(/(`[^`]*`)/g)
        .map((part) => (part.startsWith("`") ? part : transform(part)))
        .join("");
    })
    .join("\n");
}

/** Rewrites repository-relative markdown links to absolute blob URLs. */
export function absoluteLinks(source: string, base: string): string {
  return mapProse(source, (text) =>
    text.replace(/\]\(([^)]+)\)/g, (match, target: string) =>
      /^(?:https?:|mailto:|#)/.test(target) ? match : `](${base}/${target})`,
    ),
  );
}

/** Escapes the characters MDX would otherwise read as expression or JSX syntax. */
export function escapeMdx(source: string): string {
  return mapProse(source, (text) =>
    text
      .replace(/<((?:https?|mailto):[^>\s]+)>/g, "[$1]($1)")
      .replace(/</g, "&lt;")
      .replace(/\{/g, "&#123;")
      .replace(/\}/g, "&#125;"),
  );
}

/** Strips the explicit-request guard and returns the first remaining sentence. */
export function summarize(description: string): string {
  const remainder = description.startsWith(guard) ? description.slice(guard.length).trim() : description.trim();
  const stop = remainder.search(/\.\s/);
  return stop === -1 ? remainder : remainder.slice(0, stop + 1);
}

function withoutGuard(description: string): string {
  return description.startsWith(guard) ? description.slice(guard.length).trim() : description.trim();
}

function titleFrom(body: string, name: string): string {
  return body.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? name;
}

function bodyWithoutTitle(body: string): string {
  return body.replace(/^#\s+.+\n+/, "").trimEnd();
}

async function listFiles(directory: string): Promise<string[]> {
  try {
    const entries = await readdir(directory, { withFileTypes: true, recursive: true });
    return entries
      .filter((entry) => entry.isFile())
      .map((entry) => path.relative(directory, path.join(entry.parentPath, entry.name)))
      .sort();
  } catch {
    return [];
  }
}

export async function readSkill(root: string, name: string): Promise<Skill> {
  const skillDir = path.join(root, "skills", name);
  const source = await readFile(path.join(skillDir, "SKILL.md"), "utf8");
  const block = source.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!block) throw new Error(`${name}: invalid frontmatter`);
  const metadata = Bun.YAML.parse(block[1]) as Record<string, unknown>;
  const description = typeof metadata.description === "string" ? metadata.description : "";
  const body = source.slice(block[0].length).trim();

  let defaultPrompt: string | undefined;
  try {
    const openai = Bun.YAML.parse(await readFile(path.join(skillDir, "agents", "openai.yaml"), "utf8")) as {
      interface?: { default_prompt?: unknown };
    };
    if (typeof openai.interface?.default_prompt === "string") defaultPrompt = openai.interface.default_prompt;
  } catch {
    defaultPrompt = undefined;
  }

  return {
    name,
    title: titleFrom(body, name),
    summary: summarize(description),
    description: withoutGuard(description),
    argumentHint: typeof metadata["argument-hint"] === "string" ? metadata["argument-hint"] : undefined,
    defaultPrompt,
    body: bodyWithoutTitle(body),
    references: await listFiles(path.join(skillDir, "references")),
    templates: await listFiles(path.join(skillDir, "templates")),
  };
}

function assetSection(skill: Skill, link: (file: string) => string): string {
  const lines: string[] = [];
  if (skill.references.length > 0) {
    lines.push("", "## References", "");
    for (const file of skill.references) lines.push(`- [\`${file}\`](${link(`references/${file}`)})`);
  }
  if (skill.templates.length > 0) {
    lines.push("", "## Templates", "");
    for (const file of skill.templates) lines.push(`- [\`${file}\`](${link(`templates/${file}`)})`);
  }
  return lines.join("\n");
}

function invocation(skill: Skill): string {
  const lines = [
    "## Invocation",
    "",
    "This skill never activates on its own. Name it in your request:",
    "",
    `> Use \`${skill.name}\` …`,
  ];
  if (skill.argumentHint !== undefined) lines.push("", `Arguments: \`${skill.argumentHint}\``);
  return lines.join("\n");
}

export function renderReadme(skill: Skill): string {
  return `${banner}

# ${skill.title}

\`${skill.name}\` — part of [tailrocks-skills](../../README.md) · [documentation](${siteUrl}/docs/skills/${skill.name})

${skill.description}

${invocation(skill)}

## Skill definition

The text below is the skill body loaded by the agent, verbatim from
[\`SKILL.md\`](SKILL.md).

---

${skill.body}
${assetSection(skill, (file) => file)}
`;
}

export function renderSkillPage(skill: Skill): string {
  const base = `${repoBlob}/skills/${skill.name}`;
  const body = escapeMdx(absoluteLinks(skill.body, base));
  return `---
title: ${skill.title}
description: ${JSON.stringify(skill.summary)}
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

\`${skill.name}\` · [source](${base}/SKILL.md) · [README](${base}/README.md)

${escapeMdx(skill.description)}

${escapeMdx(invocation(skill))}

## Skill definition

The text below is the skill body loaded by the agent, verbatim from its source.

---

${body}
${escapeMdx(assetSection(skill, (file) => `${base}/${file}`))}
`;
}

export function renderSkillIndex(skills: readonly Skill[]): string {
  const rows = escapeMdx(
    skills.map((skill) => `| [\`${skill.name}\`](/docs/skills/${skill.name}) | ${skill.summary} |`).join("\n"),
  );
  return `---
title: Skills
description: "Every skill in the collection, with what it is for."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

Every skill is manual-only: it runs when you name it, never on its own.

| Skill | What it does |
|---|---|
${rows}
`;
}

export function renderSkillMeta(skills: readonly Skill[]): string {
  return `${JSON.stringify({ title: "Skills", pages: ["index", ...skills.map((skill) => skill.name)] }, null, 2)}\n`;
}

export function renderRootList(skills: readonly Skill[]): string {
  const rows = skills.map((skill) => `| [\`${skill.name}\`](skills/${skill.name}/README.md) | ${skill.summary} |`);
  return `${listStart}

| Skill | What it does |
|---|---|
${rows.join("\n")}

${listEnd}`;
}

export function replaceRootList(readme: string, list: string): string {
  const start = readme.indexOf(listStart);
  const end = readme.indexOf(listEnd);
  if (start === -1 || end === -1) throw new Error(`README.md is missing the ${listStart} / ${listEnd} markers`);
  return `${readme.slice(0, start)}${list}${readme.slice(end + listEnd.length)}`;
}

export function renderInstallPage(install: string): string {
  const body = escapeMdx(absoluteLinks(install.replace(/^#\s+.+\n+/, "").trimEnd(), repoBlob));
  return `---
title: Installing
description: "Install the collection in Claude Code, Codex, OpenCode, Grok Build, Kimi Code, Antigravity, or Amp."
---

{/* ${banner.replace(/^<!--\s*|\s*-->$/g, "")} */}

${body}
`;
}

export async function generate(root: string): Promise<Generated[]> {
  const names = (await readdir(path.join(root, "skills"), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const skills: Skill[] = [];
  for (const name of names) skills.push(await readSkill(root, name));

  const output: Generated[] = [];
  for (const skill of skills) {
    output.push({ file: path.join("skills", skill.name, "README.md"), content: renderReadme(skill) });
    output.push({
      file: path.join("docs", "content", "docs", "skills", `${skill.name}.mdx`),
      content: renderSkillPage(skill),
    });
  }
  output.push({
    file: path.join("docs", "content", "docs", "skills", "index.mdx"),
    content: renderSkillIndex(skills),
  });
  output.push({
    file: path.join("docs", "content", "docs", "skills", "meta.json"),
    content: renderSkillMeta(skills),
  });
  output.push({
    file: path.join("docs", "content", "docs", "install.mdx"),
    content: renderInstallPage(await readFile(path.join(root, "INSTALL.md"), "utf8")),
  });
  output.push({
    file: "README.md",
    content: replaceRootList(await readFile(path.join(root, "README.md"), "utf8"), renderRootList(skills)),
  });
  return output;
}

async function currentContent(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

if (import.meta.main) {
  const root = path.resolve(import.meta.dir, "..");
  const check = process.argv.includes("--check");
  const generated = await generate(root);
  const stale: string[] = [];
  for (const { file, content } of generated) {
    const target = path.join(root, file);
    if ((await currentContent(target)) === content) continue;
    stale.push(file);
    if (check) continue;
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content);
  }
  if (check && stale.length > 0) {
    for (const file of stale) console.error(`error: out of date, run 'mise run docs': ${file}`);
    process.exit(1);
  }
  console.log(check ? `Checked ${generated.length} generated files.` : `Wrote ${stale.length}/${generated.length} files.`);
}
